name: Continuous Integration
on:
  schedule:
    - cron: "0 0 * * 2"
  push:
    branches:
      - main
      - staging
      - trying
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - "pyvisa_py/**"
      - pyproject.toml
      - setup.py

jobs:
  formatting:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort mypy pytest
          pip install git+https://github.com/pyvisa/pyvisa.git@main
      - name: Isort
        run: |
          isort pyvisa_py -c;
      - name: Black
        if: always()
        run: |
          black pyvisa_py --check;
      - name: Flake8
        if: always()
        run: |
          flake8 pyvisa_py;
      - name: Mypy
        if: always()
        run: |
          mypy pyvisa_py;
  tests:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/pyvisa/pyvisa.git#egg=pyvisa
      - name: Install project
        run: |
          pip install -e .
      - name: Test with pytest
        run: |
          pip install pytest-cov
          pytest pyvisa_py/testsuite --cov pyvisa_py --cov-report xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

  # Added to summarize the matrix (otherwise we would need to list every single
  # job in bors.toml)
  tests-result:
    name: Tests result
    if: always()
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
      - name: Mark the job as a success
        if: needs.tests.result == 'success'
        run: exit 0
      - name: Mark the job as a failure
        if: needs.tests.result != 'success'
        run: exit 1
